### ISSUE TITLE
[FEATURE] Add Search Bar to Filter Specific Components

### ISSUE THREAD

**Issue by RaiDevX8** [Jaishree2310/GlassyUI-Components#88] opened 2024-10-09 16:14 UTC
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

✅ I have checked "open" AND "closed" issues and this is not a duplicate

### Proposed Solution

This feature request is related to unavailable functionality. when trying to find specific components on the home page, as there is currently no way to filter or search through them efficiently.. I propose adding a search bar on the home page, positioned between the logo and the "Generate Class Effect" element. This search bar should allow users to filter out specific components dynamically as they type

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

1. Add the Search Input in the Homepage
     Add a search input field to the homepage, positioned between the logo and the "Generate Class Effect" element.
     This input will be a controlled form element, allowing the search query to be captured and managed via the component’s state.
2.Implement the Filtering Logic
 Implement a filtering mechanism that dynamically updates the displayed components based on the user’s search input.
   The components should be filtered by name, description, or other relevant fields, ensuring that the search is case-insensitive.
3.  Ensure the search bar visually aligns with the existing homepage design, maintaining consistency with other UI elements.
    Style it to be responsive and user-friendly, considering padding, margins, and input field size.

**Comment by Ameerjafar** [comment] 2024-10-13 03:14
@Jaishree2310 is the issue is still open to work on

**Comment by Jaishree2310** [comment] 2024-10-15 18:20
@Ameerjafar I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by Ameerjafar** [comment] 2024-10-15 19:41
@Jaishree2310 I have raised the pr can you kindly review that.

**Comment by RaiDevX8** [comment] 2024-10-16 03:44
I have done what you did to put every component in the array.... But it changes cards design

**Comment by Ameerjafar** [comment] 2024-10-16 04:48
@RaiDevX8 it won't because i did not change the component card, it is the responsible of the design. what i have done is what are the component has to go under the component card. i have attached the video in my pr you can go and check that out.

**Closed** 2024-10-16 06:02 UTC
Labels: enhancement, good first issue, gssoc-ext, level2
